name: Publish NPM

on:
  workflow_call:
    inputs:
      node_version:
        default: '18'
        type: string
        required: false
      workspace:
        default: ''
        type: string
        required: false

jobs:
  publish_npm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: ${{ inputs.node_version }}
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - name: Publish
        if: ${{ inputs.workspace == '' }}
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish --access public
      - name: Publish workspace
        if: ${{ inputs.workspace != '' }}
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish -w ${{ inputs.workspace }} --access public
