# https://docs.github.com/en/actions/using-workflows/reusing-workflows

name: Lint, test and build

on:
  workflow_call:
    inputs:
      node_version:
        default: "20"
        type: string
        required: false

jobs:
  test_and_lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: ${{ inputs.node_version }}
      - name: install
        run: npm ci
      - name: lint
        run: npm run lint
      - name: test
        run: npm run test
      - name: audit
        run: npm audit --audit-level=high
      - name: build
        run: npm run build
